# Generated by Django 5.1.1 on 2024-09-28 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_booking', models.DateTimeField()),
                ('end_booking', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=256)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=256, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.activity')),
                ('staff', models.ManyToManyField(to='booking.staff')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.place'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('ENG', 'Engineering'), ('BUS', 'Business'), ('MED', 'Medicine'), ('LAW', 'Law'), ('ART', 'Arts'), ('EDU', 'Education'), ('BIO', 'Biology'), ('CHE', 'Chemistry'), ('PHY', 'Physics'), ('MATH', 'Mathematics'), ('SOC', 'Social Sciences'), ('HIST', 'History'), ('PHIL', 'Philosophy'), ('ENV', 'Environmental Science')], max_length=50)),
                ('stu_card', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('photo', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.place')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.student')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.student'),
        ),
    ]
