# Generated by Django 5.1.1 on 2024-10-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start',
            new_name='start_time',
        ),
    ]
