# Generated by Django 5.0.6 on 2024-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_created_at_report_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingfile',
            name='image',
            field=models.ImageField(null=True, upload_to='studentcard/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo',
            field=models.ImageField(null=True, upload_to='place/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='REPORTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('ENG', 'Engineering'), ('BUS', 'Business'), ('MED', 'Medicine'), ('LAW', 'Law'), ('ART', 'Arts'), ('EDU', 'Education'), ('SC', 'Sciences')], max_length=50),
        ),
    ]
